[theme]
# Primary accent color for interactive elements.
primaryColor = "#4e5154"  #Grey

# Background color for the main content area.
backgroundColor = "#ffffff" #White background

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#b8dcff"  #Light Blue

# Color used for almost all text.
textColor = "#000000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
